### ISSUE TITLE
OCAMicroBrk compile issue

### ISSUE THREAD

**Issue by diboxes** [OCAAlliance/OCAMicro#1]
Error	12	error C1083: Cannot open source file: '..\..\..\Src\app\OCALiteDante\OcaLiteNetworkSignalChannel.cpp': No such file or directory	j:\OCAMicro-master\OCAMicro\OCAMicro\Src\app\OCA_BKNII\c1xx	OCAMicroBrk

**Comment by tljdebrouwer** [comment]
Thanks for reporting this. I did some reshuffling to remove some duplicate files. probably missed out some make files while doing this.

**Comment by tljdebrouwer** [comment]
OCAMicroBrk was incorrectly marked to be able to build on Windows (for release). OCAMicroBrk is targeted for a uBlaze platform. I will fix this.

**Comment by tljdebrouwer** [comment]
"Fixed" with commit 49 for windows. Will verify compilation on uBlaze
