### ISSUE TITLE
OCALiteDante Compile Issue

### ISSUE THREAD

**Issue by diboxes** [OCAAlliance/OCAMicro#2]
Error	6	error LNK2019: unresolved external symbol "protected: __thiscall OcaLiteStreamNetwork::OcaLiteStreamNetwork(unsigned int,bool,class OcaLiteString const &,enum OcaLiteNetworkLinkType,class OcaLiteBlobDataType const &,enum OcaLiteNetworkControlProtocol,enum OcaLiteNetworkMediaProtocol)" (??0OcaLiteStreamNetwork@@IAE@I_NABVOcaLiteString@@W4OcaLiteNetworkLinkType@@ABVOcaLiteBlobDataType@@W4OcaLiteNetworkControlProtocol@@W4OcaLiteNetworkMediaProtocol@@@Z) referenced in function "public: __thiscall OcaLiteStreamNetworkDante::OcaLiteStreamNetworkDante(unsigned int,bool,class OcaLiteString const &,class OcaLiteStringInABlob const &)" (??0OcaLiteStreamNetworkDante@@QAE@I_NABVOcaLiteString@@ABVOcaLiteStringInABlob@@@Z)	j:\OCAMicro-master\OCAMicro\OCAMicro\Src\app\OCALiteDante\OcaLiteStreamNetworkDante.obj	OCALiteDante

**Comment by tljdebrouwer** [comment]
Some project files were not correctly updated. Please note that you do need to be a Dante licensee to be able to compile this executable completely.

**Comment by tljdebrouwer** [comment]
Fixed with commit 49.
