### ISSUE TITLE
Is this demo based on AES70-2015?

### ISSUE THREAD

**Issue by Ssscy** [OCAAlliance/OCAMicro#28]
HI，
I find some class can not be found in AES70-2-2018-AnnexA.eap
so I download AES70-2-AnnexA-151112-class-structure-1.eap and that's ok

do u have demo base on AES70-2018? 

thanks

**Comment by tljdebrouwer** [comment]
Hi @Ssscy ,

No, this demo is currently based on AES70-2015.
