### ISSUE TITLE
OCA Browser question

### ISSUE THREAD

**Issue by andrew-elder** [OCAAlliance/OCAMicro#3]
The OcaMicro Guide document refers to an "OCA Browser" application. I don't see the browser as part of the OCAMicro code base?

**Comment by tljdebrouwer** [comment]
The OCABrowser is one of the programs you get for free when you become on OCA Alliance member. I will make sure this gets reflected into the document better (see http://ocaalliance.com/membership/benefits/). Please let me know if there are any additional question about this.

**Comment by andrew-elder** [comment]
Thanks!

**Comment by andrew-elder** [comment]
Is the OCABrowser available for both Full and Associate membership levels?

**Comment by tljdebrouwer** [comment]
It’s just there on the member portal. So Yes.
